### ISSUE TITLE
Initial conditions are not necessarily a `NamedTuple`.

### ISSUE THREAD

**Issue by benedict-96** [JuliaGNI/GeometricEquations.jl#16]
If I want to build an `EnsembleProblem` the initial conditions need to be `NamedTuple`s (https://github.com/JuliaGNI/GeometricEquations.jl/blob/main/src/problems/ensemble_problem.jl), but sometimes they are not in that form (in e.g. https://github.com/JuliaGNI/GeometricProblems.jl/blob/main/src/lotka_volterra_3d.jl). 
Can the constructor easily be generalized to the case when the initial conditions are an Array and not a NamedTuple?

**Comment by michakraus** [comment]
Appropriate convenience constructors have been implemented in 454357479e37d15253dde182a808de01efddb685 for all `*ODEEnsemble` types. They are still missing for the `*DAEEnsemble` types, though.
