### ISSUE TITLE
Missing constructor for multiple parameters and a single set of ics for `HODEEnsemble`.

### ISSUE THREAD

**Issue by benedict-96** [JuliaGNI/GeometricEquations.jl#18]
There is a missing constructor for `HODEEnsemble`:
https://github.com/JuliaGNI/GeometricEquations.jl/blob/f8c23c7fdbe6f558fe718c7aff2716c1a1c2b43a/src/odes/hode.jl#L252-L269

I should take two vectors (`Vector{<:Number}`) or `StateVariable`s as input and the parameters should be a vector of `NamedTuple`s. https://github.com/JuliaGNI/GeometricProblems.jl/pull/66 can only be merged once this constructor is implemented.

**Comment by michakraus** [comment]
Should be fixed by 427c03726d3b0be410e500e7c75e23e2e2a6631c.
